EXECS = p1 p2 p3 p4 p5 p6

all:	$(EXECS)

p1:	p1-basic.cc
	g++ -o p1 p1-basic.cc

p2:	p2-morph.cc
	g++ -o p2 p2-morph.cc

p3:	p3-dest.cc
	g++ -o p3 p3-dest.cc

p4:	p4-abs.cc
	g++ -o p4 p4-abs.cc

p5:	p5-vect.cc
	g++ -o p5 p5-vect.cc

p6:	p6-dyn.cc
	g++ -o p6 p6-dyn.cc

clean:
	rm -f $(EXECS)
